// 全局
export const UPDATE_TIP = 'UPDATE_TIP'
export const UPDATE_DIALOG_SETTINGS = 'UPDATE_DIALOG_SETTINGS'
export const UPDATE_BACK_STATUS = 'UPDATE_BACK_STATUS'

export const UPDATE_HEADER = 'UPDATE_HEADER' // 更新header
export const UPDATE_FOOTER = 'UPDATE_FOOTER' // 更新footer
export const SET_PAGE_ANIMATE_TYPE = 'SET_PAGE_ANIMATE_TYPE'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const UPDATE_MANUAL_CLOSE_LOADING = 'UPDATE_MANUAL_CLOSE_LOADING'

// 微信
export const UPDATE_WECHAT_INITD_STATUS = 'UPDATE_WECHAT_INITD_STATUS'

// 用户
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO' // 更新用户信息
export const UPDATE_API_TOKEN = 'UPDATE_API_TOKEN' // 更新API_TOKEN
